name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          cli: "latest"
          sdk: "5.7.1"
          ccache-variant: sccache

      - uses: actions/upload-artifact@v4
        with:
          name: Windows Build Output
          path: build/*.geode

  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          cli: "latest"
          sdk: "5.7.1"

      - uses: actions/upload-artifact@v4
        with:
          name: macOS Build Output
          path: build/*.geode

  build-android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          cli: "latest"
          sdk: "5.7.1"
          target: "android64"

      - uses: actions/upload-artifact@v4
        with:
          name: Android Build Output
          path: build/*.geode

  build-android32:
    name: Android (32-bit)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          cli: "latest"
          sdk: "5.7.1"
          target: "android32"

      - uses: actions/upload-artifact@v4
        with:
          name: Android32 Build Output
          path: build/*.geode

  build-ios:
    name: iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          cli: "latest"
          sdk: "5.7.1"
          target: "ios"

      - uses: actions/upload-artifact@v4
        with:
          name: iOS Build Output
          path: build/*.geode
